"""Plain-English one-line descriptions for endpoints whose code has no summary."""

SUMMARIES = {
    "GET /api/v1/me/notifications/unread-count": "Number of unread notifications. Use it for the bell badge.",
    "POST /api/v1/me/notifications/{id}/read": "Mark one notification as read.",
    "POST /api/v1/me/notifications/read-all": "Mark all my notifications as read.",
    "PUT /api/v1/me/notifications/preferences": "Turn notification channels (in-app, email, SMS) on or off per notification type.",
    "PATCH /api/v1/dealer/profile": "Update my dealership details.",
    "GET /api/v1/dealer/documents": "List the verification documents my dealership uploaded.",
    "GET /api/v1/dealer/branches": "List my dealership's branches.",
    "POST /api/v1/dealer/branches": "Add a branch.",
    "PATCH /api/v1/dealer/branches/{id}": "Update a branch, or deactivate it with isActive=false.",
    "GET /api/v1/dealer/staff": "List staff members with their roles and effective permissions.",
    "GET /api/v1/dealer/staff/{memberId}/activity": "Recent actions performed by one staff member.",
    "GET /api/v1/admin/dealers": "List dealers. Filter by status, province or text.",
    "GET /api/v1/admin/dealers/{id}": "Full dealer record: branches, members, documents (with download links) and stats.",
    "GET /api/v1/catalogue/features": "All vehicle features (safety, comfort, technology...).",
    "GET /api/v1/admin/catalogue/makes": "List all makes, including inactive ones.",
    "POST /api/v1/admin/catalogue/makes": "Create a make.",
    "PATCH /api/v1/admin/catalogue/makes/{id}": "Update a make.",
    "GET /api/v1/admin/catalogue/makes/{makeId}/models": "List the models of a make.",
    "POST /api/v1/admin/catalogue/models": "Create a model.",
    "PATCH /api/v1/admin/catalogue/models/{id}": "Update a model.",
    "DELETE /api/v1/admin/catalogue/models/{id}": "Delete a model. Fails with 409 if variants or vehicles still use it.",
    "POST /api/v1/admin/catalogue/generations": "Create a generation (for example BMW 3 Series G20).",
    "PATCH /api/v1/admin/catalogue/generations/{id}": "Update a generation.",
    "DELETE /api/v1/admin/catalogue/generations/{id}": "Delete a generation.",
    "GET /api/v1/admin/catalogue/models/{modelId}/variants": "List the variants of a model with their specifications.",
    "POST /api/v1/admin/catalogue/variants": "Create a variant, optionally with its full specification.",
    "PATCH /api/v1/admin/catalogue/variants/{id}": "Update a variant and/or its specification.",
    "DELETE /api/v1/admin/catalogue/variants/{id}": "Delete a variant.",
    "GET /api/v1/admin/catalogue/categories": "List all vehicle categories.",
    "POST /api/v1/admin/catalogue/categories": "Create a vehicle category.",
    "PATCH /api/v1/admin/catalogue/categories/{id}": "Update a vehicle category.",
    "DELETE /api/v1/admin/catalogue/categories/{id}": "Delete a vehicle category.",
    "POST /api/v1/admin/catalogue/features": "Create a feature.",
    "PATCH /api/v1/admin/catalogue/features/{id}": "Update a feature.",
    "DELETE /api/v1/admin/catalogue/features/{id}": "Delete a feature.",
    "DELETE /api/v1/admin/catalogue/feature-assignments/{id}": "Remove a feature from a make, model, generation or variant.",
    "GET /api/v1/vehicles/{id}/similar": "Similar vehicles (same model first, then same body type at a similar price).",
    "GET /api/v1/vehicles/{id}/dealer-vehicles": "Other vehicles from the same dealer.",
    "GET /api/v1/dealer/vehicles/{id}": "One vehicle from my inventory, with photos, history and allowed next actions.",
    "POST /api/v1/dealer/vehicles/{id}/release": "Cancel a reservation. The vehicle becomes available again.",
    "POST /api/v1/dealer/vehicles/{id}/unsuspend": "Put a suspended listing back online.",
    "GET /api/v1/dealer/vehicles/{id}/images": "List the photos of a vehicle.",
    "PUT /api/v1/dealer/vehicles/{id}/images/order": "Set photo order. The first photo becomes the main photo.",
    "PATCH /api/v1/dealer/vehicles/{id}/images/{imageId}": "Set alt text or make a photo the main photo.",
    "DELETE /api/v1/dealer/vehicles/{id}/images/{imageId}": "Delete a photo.",
    "GET /api/v1/admin/vehicles": "List all vehicles. Filter by dealer, status or text.",
    "GET /api/v1/admin/vehicles/{id}": "Full vehicle record including private fields and history.",
    "PATCH /api/v1/admin/vehicles/{id}": "Edit a vehicle as an administrator (same edit rules as dealers).",
    "POST /api/v1/admin/vehicles/{id}/approve": "Approve a listing that is waiting for review.",
    "POST /api/v1/admin/vehicles/{id}/reject": "Reject a listing. A reason is required.",
    "POST /api/v1/admin/vehicles/{id}/publish": "Publish an approved listing on behalf of the dealer.",
    "POST /api/v1/admin/vehicles/{id}/suspend": "Take a listing offline. A reason is required. Only an admin can bring it back.",
    "POST /api/v1/admin/vehicles/{id}/unsuspend": "Put a suspended listing back online.",
    "POST /api/v1/admin/vehicles/{id}/archive": "Archive a listing.",
    "GET /api/v1/dealer/leads/{id}": "One lead with its enquiry, vehicle, deal and full activity history.",
    "PATCH /api/v1/dealer/leads/{id}": "Update lead contact details, vehicle or next follow-up date.",
    "POST /api/v1/dealer/leads/{id}/assign": "Assign a lead to a staff member, or unassign it with null.",
    "GET /api/v1/me/enquiries/{id}": "One of my enquiries with the full conversation.",
    "POST /api/v1/me/enquiries/{id}/reply": "Send a follow-up message on my enquiry.",
    "POST /api/v1/me/enquiries/{id}/cancel": "Cancel my enquiry.",
    "GET /api/v1/dealer/enquiries": "Enquiries sent to my dealership (or my branch).",
    "GET /api/v1/dealer/enquiries/{id}": "One enquiry with the conversation and its lead.",
    "GET /api/v1/admin/enquiries": "All enquiries. Use platformOnly=true for requests handled by the ChangeCars team.",
    "GET /api/v1/admin/enquiries/{id}": "One enquiry with customer, dealer, vehicle and conversation.",
    "POST /api/v1/admin/enquiries/{id}/respond": "Reply to an enquiry as the ChangeCars team.",
    "POST /api/v1/me/sell-requests/{id}/cancel": "Cancel my sell request. Open bidding is cancelled too.",
    "POST /api/v1/me/sell-requests/{id}/images/upload-url": "Step 1 of a photo upload: get a presigned upload URL.",
    "POST /api/v1/me/sell-requests/{id}/images": "Step 2 of a photo upload: confirm the uploaded photo.",
    "GET /api/v1/admin/sell-requests": "List sell and valuation requests.",
    "GET /api/v1/admin/sell-requests/{id}": "Full sell request with valuations, bidding sessions, offers and deal.",
    "PATCH /api/v1/admin/sell-requests/{id}/status": "Change the status (review, reject, complete, cancel).",
    "GET /api/v1/admin/bidding-sessions": "List bidding sessions.",
    "POST /api/v1/admin/bidding-sessions/{id}/cancel": "Cancel a bidding process. Active offers are rejected.",
    "GET /api/v1/dealer/bidding/sessions/{id}": "One bidding session with vehicle details and my offer history.",
    "POST /api/v1/dealer/offers/{id}/withdraw": "Withdraw my offer (only if the session allows withdrawals).",
    "POST /api/v1/me/offers/{id}/reject": "Reject a dealer's offer.",
    "PATCH /api/v1/me": "Update my name, phone or marketing consent.",
    "DELETE /api/v1/me/sessions/{id}": "Sign out one device.",
    "PUT /api/v1/me/favourites/{vehicleId}": "Save a vehicle to favourites. Safe to call twice.",
    "DELETE /api/v1/me/favourites/{vehicleId}": "Remove a vehicle from favourites.",
    "POST /api/v1/me/saved-searches": "Save the current search filters, with optional alerts.",
    "DELETE /api/v1/me/saved-searches/{id}": "Delete a saved search.",
    "DELETE /api/v1/me/recently-viewed": "Clear my recently viewed history.",
    "GET /api/v1/content/articles/{slug}": "One published article with its content blocks.",
    "GET /api/v1/content/article-categories": "Article categories.",
    "GET /api/v1/content/media/{slug}": "One published video or podcast.",
    "GET /api/v1/content/faqs": "Frequently asked questions. Filter with ?category=.",
    "GET /api/v1/promotions/{slug}": "One promotion with its vehicles (paginated).",
    "GET /api/v1/admin/articles": "List articles (all statuses).",
    "POST /api/v1/admin/articles": "Create an article (starts as DRAFT).",
    "GET /api/v1/admin/articles/{id}": "One article including drafts.",
    "PATCH /api/v1/admin/articles/{id}": "Update an article.",
    "DELETE /api/v1/admin/articles/{id}": "Delete an article.",
    "POST /api/v1/admin/article-categories": "Create an article category.",
    "DELETE /api/v1/admin/article-categories/{id}": "Delete an article category.",
    "GET /api/v1/admin/media": "List videos and podcasts.",
    "POST /api/v1/admin/media": "Add a video or podcast (starts as DRAFT).",
    "PATCH /api/v1/admin/media/{id}": "Update a video or podcast.",
    "DELETE /api/v1/admin/media/{id}": "Delete a video or podcast.",
    "POST /api/v1/admin/media/{id}/status": "Publish, unpublish or archive a video or podcast.",
    "GET /api/v1/admin/faqs": "List all FAQs.",
    "POST /api/v1/admin/faqs": "Create an FAQ.",
    "PATCH /api/v1/admin/faqs/{id}": "Update an FAQ.",
    "DELETE /api/v1/admin/faqs/{id}": "Delete an FAQ.",
    "GET /api/v1/admin/pages": "List static pages.",
    "POST /api/v1/admin/pages": "Create a static page.",
    "GET /api/v1/admin/pages/{id}": "One static page.",
    "PATCH /api/v1/admin/pages/{id}": "Update a static page.",
    "DELETE /api/v1/admin/pages/{id}": "Delete a static page.",
    "POST /api/v1/admin/pages/{id}/status": "Publish or unpublish a static page.",
    "GET /api/v1/admin/promotions": "List promotions.",
    "POST /api/v1/admin/promotions": "Create a promotion.",
    "PATCH /api/v1/admin/promotions/{id}": "Update a promotion.",
    "DELETE /api/v1/admin/promotions/{id}": "Delete a promotion. Its vehicles are detached.",
    "POST /api/v1/newsletter/subscribe": "Subscribe an email address to the newsletter.",
    "GET /api/v1/admin/newsletter/subscribers": "List newsletter subscribers.",
    "GET /api/v1/admin/newsletter/subscribers.csv": "Download subscribers as a CSV file.",
    "GET /api/v1/admin/users": "List users. Filter by role, status or text.",
    "GET /api/v1/admin/users/{id}": "One user with dealer membership and activity counts.",
    "PATCH /api/v1/admin/users/{id}/role": "Change a user's platform role. The user is signed out everywhere.",
    "GET /api/v1/admin/system/outbox/events": "Background events by status (default: failed/dead events).",
    "GET /api/v1/seo/sitemap-static.xml": "Sitemap of home, makes, models, dealers, articles and pages.",
    "GET /api/v1/seo/sitemap-vehicles-{page}.xml": "Sitemap of vehicle pages, 10 000 per file.",
}
